### ISSUE TITLE
Make playbook idempotent

### ISSUE THREAD

**Issue by ichayer** [ThomasMiz/ansible-demo#1]
I don't want to push this yet, because we can still debug using the 'nohup.out' to understand why the web server does not run. This is what we should add afterwards:

```yml
   - name: Copy systemd reddy.service 
     ansible.builtin.copy:
        src: ./files/reddy.service
        dest: /etc/systemd/system/reddy.service
        owner: root
        group: root
        mode: '0644'

   - name: Reload the systemd configuration
     ansible.builtin.systemd:
        daemon_reexec: yes

   - name: Enable and start the service
     ansible.builtin.service:
        name: reddy
        enabled: yes
        state: started

```
